version: '3.8'
services:
  app:
      build:
        context: ./
        dockerfile: dockerfile
      image: sacolinha_api
      env_file:
        - .env 
      ports:
        - "3000:3000"
      volumes:
        - ./uploads:/app/uploads
        - ./dist:/app/dist

      restart: always